[project]
name = "random-network-distillation-pytorch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ale-py>=0.10.1",
    "gymnasium>=1.0.0",
    "opencv-python>=4.10.0.84",
    "tensorboard>=2.18.0",
    "torch>=2.5.1",
]
